name: Prod Feedback Cronjob

on:
  push:
    branches:
      - "feedback-bot"
    schedule:
      # 8AM EST
      # 1PM UTC
      - cron: "0 13 * * *"

jobs:
  run_cronjob:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bhasa-bot
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          DISCORD_WEBHOOK_ENDPOINT: ${{ secrets.DISCORD_WEBHOOK_ENDPOINT }}
        run: |
          python main.py
